#############################################################################
# Makefile for building: puncher
# Generated by qmake (3.0) (Qt 5.1.0) on: sex Abr 3 18:28:21 2015
# Project:  puncher.pro
# Template: app
# Command: /home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/bin/qmake -o Makefile puncher.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = /home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: puncher.pro ../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/win32-g++/qmake.conf ../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/spec_pre.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/qdevice.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/device_config.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/common/shell-unix.conf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/qconfig.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_core.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_network.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qico.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qwindows.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/qt_functions.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/qt_config.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/win32-g++/qmake.conf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/spec_post.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/exclusive_builds.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/default_pre.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/win32/default_pre.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/resolve_config.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/default_post.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/win32/rtti.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/warn_on.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/qt.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/resources.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/moc.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/win32/opengl.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/uic.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/win32/windows.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/testcase_targets.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/exceptions.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/yacc.prf \
		../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/lex.prf \
		puncher.pro \
		/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/lib/Qt5PrintSupport.prl \
		/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/lib/Qt5Widgets.prl \
		/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/lib/Qt5Gui.prl \
		/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/lib/Qt5Core.prl \
		/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/lib/Qt5Sql.prl \
		/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/plugins/platforms/qwindows.prl \
		/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/lib/Qt5PlatformSupport.prl
	$(QMAKE) -o Makefile puncher.pro
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/spec_pre.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/qdevice.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/device_config.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/common/shell-unix.conf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/qconfig.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_bootstrap.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_core.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_dbus.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_gui.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_network.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_opengl.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_platformsupport.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_sql.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_testlib.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_widgets.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_lib_xml.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qico.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qminimal.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qnativewifibearer.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_qwindows.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/qt_functions.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/qt_config.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/win32-g++/qmake.conf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/spec_post.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/exclusive_builds.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/default_pre.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/win32/default_pre.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/resolve_config.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/default_post.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/win32/rtti.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/warn_on.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/qt.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/resources.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/moc.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/win32/opengl.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/uic.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/win32/windows.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/testcase_targets.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/exceptions.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/yacc.prf:
../../../qt.projects/mxe/usr/i686-pc-mingw32/qt5/mkspecs/features/lex.prf:
puncher.pro:
/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/lib/Qt5PrintSupport.prl:
/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/lib/Qt5Widgets.prl:
/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/lib/Qt5Gui.prl:
/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/lib/Qt5Core.prl:
/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/lib/Qt5Sql.prl:
/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/plugins/platforms/qwindows.prl:
/home/luisfilipedias/qt.projects/mxe/usr/i686-pc-mingw32/qt5/lib/Qt5PlatformSupport.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile puncher.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) /home/luisfilipedias/00_Code/02_Code/puncher/puncher_plugin_import.cpp

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
